# PyInstaller spec for NetWatch Desktop.
#   pyinstaller packaging/netwatch.spec --noconfirm
#
# Produces dist/NetWatch/NetWatch.exe (one-dir: faster start than one-file and
# lets the installer patch individual files on update).

import os
import sys
from pathlib import Path
from PyInstaller.utils.hooks import collect_all, collect_data_files

ROOT = Path(SPECPATH).resolve().parent          # noqa: F821 (SPECPATH is injected)
APP = ROOT / "app"

# Which product is being built.
#   retail   -> "NetWatch"          licensed/community basemaps only
#   personal -> "NetWatch Personal" adds Google's scraped tiles; DO NOT SELL
EDITION = os.environ.get("NETWATCH_EDITION", "retail").strip().lower()
if EDITION not in ("retail", "personal"):
    EDITION = "retail"
EXE_NAME = "NetWatch" if EDITION == "retail" else "NetWatchPersonal"

# Bake the edition in: a shipped binary must not be switchable via an env var.
(APP / "netwatch" / "_build_edition.py").write_text(
    '"""Generated by packaging/netwatch.spec. Do not edit."""\n'
    f'EDITION = "{EDITION}"\n',
    encoding="utf-8",
)
print(f"building NetWatch edition={EDITION} exe={EXE_NAME}.exe")

datas = [
    (str(APP / "netwatch" / "web"), "netwatch/web"),
]

# Ship the prebuilt firmware if it has been built (see firmware/build_prebuilt.ps1).
prebuilt = ROOT / "firmware" / "prebuilt"
if prebuilt.exists():
    # Ship one folder per chip, skipping any whose name starts with "_" — that
    # marks a build deliberately held back (currently _nrf52840.unverified,
    # which flashes but does not boot). Shipping it would hand customers a dead
    # board; the app reports "no bundled firmware" for that chip instead.
    shipped = [d for d in prebuilt.iterdir()
               if d.is_dir() and not d.name.startswith("_")]
    for d in shipped:
        datas.append((str(d), f"firmware/prebuilt/{d.name}"))
    held = [d.name for d in prebuilt.iterdir() if d.is_dir() and d.name.startswith("_")]
    print(f"bundling firmware for: {', '.join(sorted(d.name for d in shipped)) or 'nothing'}")
    if held:
        print(f"NOT bundling (held back): {', '.join(sorted(held))}")

# Ship the firmware sketches as reference alongside the prebuilt images.
for _sk in (ROOT / "firmware").glob("NetWatch_Beacon*"):
    if _sk.is_dir() and (_sk / f"{_sk.name}.ino").exists():
        datas.append((str(_sk), f"firmware/{_sk.name}"))
        print(f"bundling firmware source: {_sk.name}")

# This used to be a for/else, which fires when the loop ends WITHOUT a break —
# i.e. always — so every build printed "firmware is missing" while bundling it.
if not prebuilt.exists():
    print("WARNING: firmware/prebuilt is missing — the app will build without "
          "flashable firmware. Run firmware/build_prebuilt.ps1 first.")

binaries, hiddenimports = [], []

# These packages carry data files and dynamic imports PyInstaller cannot infer.
# unicorn/fs/pyelftools are anisette's dependencies and are imported lazily.
for pkg in ("findmy", "anisette", "esptool", "serial", "unicorn", "fs", "elftools", "nordicsemi"):
    try:
        d, b, h = collect_all(pkg)
        datas += d
        binaries += b
        hiddenimports += h
    except Exception as exc:
        print(f"WARNING: could not collect {pkg}: {exc}")

# anisette executes Apple's provisioning libraries inside a Unicorn CPU
# emulator. Unicorn's loader looks for its native library at <pkg>/lib/, so the
# DLL has to land there exactly -- collect_all alone drops it at the root and
# the app dies with "Failed to load the Unicorn dynamic library".
try:
    import unicorn as _unicorn
    _ulib = Path(_unicorn.__file__).parent / "lib"
    if _ulib.is_dir():
        # Only the runtime shared library. The directory also holds
        # unicorn.lib, a ~49 MB static import library used at compile time
        # and never at runtime - shipping it doubles the download for nothing.
        _found = False
        for _f in _ulib.iterdir():
            if _f.suffix.lower() in (".dll", ".so", ".dylib"):
                datas.append((str(_f), "unicorn/lib"))
                print(f"bundling unicorn runtime lib: {_f.name} "
                      f"({_f.stat().st_size / 1048576:.1f} MB)")
                _found = True
        if not _found:
            print("WARNING: no unicorn shared library found; Apple sign-in will fail")
    else:
        print("WARNING: unicorn/lib not found; Apple sign-in will fail in the bundle")
except Exception as exc:
    print(f"WARNING: could not locate the unicorn library: {exc}")

# Belt and braces: drop any static import libraries other hooks dragged in.
datas = [d for d in datas if not str(d[0]).lower().endswith((".lib", ".a"))]

hiddenimports += [
    "netwatch", "netwatch.server", "netwatch.appleclient", "netwatch.flasher",
    "netwatch.keyinject", "netwatch.store", "netwatch.secretbox",
    "netwatch.tags", "netwatch.exports", "netwatch.config",
    "netwatch.atakbridge", "netwatch.dfu", "netwatch.uf2",
    "cryptography.hazmat.primitives.ciphers.aead",
    "serial.tools.list_ports",
    # adafruit-nrfutil, used in-process to DFU the nRF52840 (netwatch/dfu.py).
    # Imported lazily, so PyInstaller cannot infer these.
    "nordicsemi", "nordicsemi.dfu.dfu",
    "nordicsemi.dfu.dfu_transport_serial", "nordicsemi.dfu.package",
]

if sys.platform.startswith("win"):
    hiddenimports += ["webview.platforms.edgechromium", "clr_loader", "pythonnet"]

a = Analysis(
    # launch.py, NOT netwatch/__main__.py: PyInstaller runs the entry script as
    # top-level __main__, which breaks that module's relative imports.
    [str(APP / "launch.py")],
    pathex=[str(APP)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "pytest"],
    noarchive=False,
)
# Do NOT ship the Visual C++ runtime.
#
# PyInstaller bundles whatever VCRUNTIME140 it finds alongside Python (seen:
# 14.42). unicorn.dll - the CPU emulator anisette uses to run Apple's
# provisioning code - is built against a newer one (seen: 14.51). Because DLLs
# resolve from the app directory first, the old copy shadows the system's and
# unicorn trips a stack-guard __fastfail: the whole process dies with
# 0xC0000409 and no Python traceback, the moment anyone signs in.
#
# Letting Windows resolve these from System32 keeps unicorn matched with the
# runtime it was compiled against. The installer verifies the VC++
# redistributable is present.
_VC_RUNTIME = {
    "vcruntime140.dll", "vcruntime140_1.dll",
    "msvcp140.dll", "msvcp140_1.dll", "msvcp140_2.dll",
}
_before = len(a.binaries)
a.binaries = [b for b in a.binaries
              if os.path.basename(b[0]).lower() not in _VC_RUNTIME]
print(f"excluded {_before - len(a.binaries)} VC++ runtime DLL(s) from the bundle")

pyz = PYZ(a.pure)                               # noqa: F821

icon = ROOT / "packaging" / "netwatch.ico"
exe = EXE(                                      # noqa: F821
    pyz, a.scripts, [],
    exclude_binaries=True,
    name=EXE_NAME,
    debug=False,
    strip=False,
    upx=False,
    console=False,                              # no console window
    icon=str(icon) if icon.exists() else None,
)
coll = COLLECT(                                 # noqa: F821
    exe, a.binaries, a.datas,
    strip=False, upx=False, name=EXE_NAME,
)
